install:
	pipx run dotbot --config-file=./dotbot.conf.yaml

subl:
	sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

link:
	#ln -s ~/Documents/dotfiles/dotfiles/dotfiles ~/.profile
	#ln -s ~/Documents/dotfiles/dotfiles/homefs/Library/Support/Sublime/Packages/User/Jasons-Mac-Mini.Preferences.sublime-settings "${HOME}/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"

perms:
	chmod 600 ~/.ssh/config
