install:
	pipx run dotbot --config-file=./dotbot.conf.yaml

subl:
	sudo ln -s "/Applications/Sublime Text.app/Contents/MacOS/sublime_text" /usr/local/bin/subl

# link:
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.bashrc ~/.bashrc
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.gitconfig ~/.gitconfig
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.gitconfig-personal ~/.gitconfig-personal
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.global.gitignore ~/.global.gitignore
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.osx ~/.osx
# 	ln -s ~/Documents/dotfiles/dotfiles/dotfiles/.profile ~/.profile
# 	ln -s ~/Documents/dotfiles/dotfiles/homefs/dotssh/config ~/.ssh/config
# 	mkdir -p ~/etc/profile.d
# 	ln -s ~/Documents/dotfiles/dotfiles/homefs/etc/profile.d/z.d ~/etc/profile.d/z.d
# 	ln -s ~/Documents/dotfiles/dotfiles/homefs/Library/Support/Sublime/Packages/User/Jasons-Mac-Mini.Preferences.sublime-settings "${HOME}/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"

perms:
	chmod 600 ~/.ssh/config
